# Generated by Django 3.2.4 on 2021-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.IntegerField()),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=250)),
            ],
        ),
    ]
